version: "2"
services:
  connector:
    build:
      # specify context - root folder of project
      context: ../
      dockerfile: ./devops/connectors/Dockerfile
    restart: always
  client-api:
    build:
      # specify context - root folder of project
      context: ../
      dockerfile: ./devops/client-api/Dockerfile
    restart: always
  zoo1:
    image: zookeeper:3.4.10
    restart: always
    container_name: cm_zookeeper1
    ports:
     - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
     - $CYBER_MARKETS_APPLICATION_DATA/zookeeper1/data:/data
     - $CYBER_MARKETS_APPLICATION_DATA/zookeeper1/datalog:/datalog
  zoo2:
    image: zookeeper:3.4.10
    restart: always
    container_name: cm_zookeeper2
    ports:
     - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
     - $CYBER_MARKETS_APPLICATION_DATA/zookeeper2/data:/data
     - $CYBER_MARKETS_APPLICATION_DATA/zookeeper2/datalog:/datalog
  zoo3:
    image: zookeeper:3.4.10
    restart: always
    container_name: cm_zookeeper3
    ports:
     - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
     - $CYBER_MARKETS_APPLICATION_DATA/zookeeper3/data:/data
     - $CYBER_MARKETS_APPLICATION_DATA/zookeeper3/datalog:/datalog
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    restart: always
    container_name: cm_kafka
    ports:
     - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka_manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      ZK_HOSTS: "zoo1:2181,zoo2:2182,zoo3:2183"
      APPLICATION_SECRET: "dilbert"