version: 2


defaults:

  container: &default_container
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk

  release_filter: &release_filter
    filters:
      tags:
        only: /^release-.*/
      branches:
        ignore: /.*/


jobs:

  build_connectors:
    <<: *default_container
    steps:
      - checkout
      - restore_cache:
          keys:
            - connectors-dependencies-{{ checksum "build.gradle" }}
            - connectors-dependencies
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
      - run:
          name: Test and build connectors project
          command: ./gradlew -p ./connectors clean build
      - save_cache:
          key: connectors-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/

  build_stream-api:
    <<: *default_container
    steps:
      - checkout
      - restore_cache:
          keys:
            - api-dependencies-{{ checksum "build.gradle" }}
            - api-dependencies
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
      - run:
          name: Test and build stream-api project
          command: ./gradlew -p ./stream-api clean build
      - save_cache:
          key: api-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/

  build_kafka-connectors:
      <<: *default_container
      steps:
        - checkout
        - restore_cache:
            keys:
              - api-dependencies-{{ checksum "build.gradle" }}
              - api-dependencies
            paths:
              - ~/.gradle/caches/
              - ~/.gradle/wrapper/
        - run:
            name: Test and build stream-api project
            command: ./gradlew -p ./stream-api clean build
        - save_cache:
            key: api-dependencies-{{ checksum "build.gradle" }}
            paths:
              - ~/.gradle/caches/
              - ~/.gradle/wrapper/

  deploy_connectors_image:
     <<: *default_container
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.05.0-ce
       - run:
           name: Build connectors docker image
           command: |
             docker build -t build/cm-connectors -f ./devops/connectors/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/cm-connectors cybernode/cm-connectors:$CIRCLE_TAG
             docker push cybernode/cm-connectors:$CIRCLE_TAG
             docker tag build/cm-connectors cybernode/cm-connectors:latest
             docker push cybernode/cm-connectors:latest

  deploy_stream-api_image:
     <<: *default_container
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.05.0-ce
       - run:
           name: Build stream-api docker image
           command: |
             docker build -t build/cm-stream-api -f ./devops/stream-api/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/cm-stream-api cybernode/cm-stream-api:$CIRCLE_TAG
             docker push cybernode/cm-stream-api:$CIRCLE_TAG
             docker tag build/cm-stream-api cybernode/cm-stream-api:latest
             docker push cybernode/cm-stream-api:latest

  deploy_stream-api_image:
       <<: *default_container
       steps:
         - checkout
         - setup_remote_docker:
             version: 17.05.0-ce
         - run:
             name: Build kafka-connectors docker image
             command: |
               docker build -t build/cm-kafka-connectors -f ./devops/stream-api/Dockerfile ./
               docker login -u $DOCKER_USER -p $DOCKER_PASS
               docker tag build/cm-kafka-connectors cybernode/cm-kafka-connectors:$CIRCLE_TAG
               docker push cybernode/cm-kafka-connectors:$CIRCLE_TAG
               docker tag build/cm-kafka-connectors cybernode/cm-kafka-connectors:latest
               docker push cybernode/cm-kafka-connectors:latest

workflows:
  version: 2

  connectors_build:
    jobs:
      - build_connectors:
          filters:
            tags:
              only: /.*/
      - deploy_connectors_image:
          <<: *release_filter
          requires:
            - build_connectors

  stream-api_build:
    jobs:
      - build_stream-api:
          filters:
            tags:
              only: /.*/
      - deploy_stream-api_image:
          <<: *release_filter
          requires:
            - build_stream-api

  kafka-connectors_build:
    jobs:
      - build_kafka-connectors:
          filters:
            tags:
              only: /.*/
      - deploy_kafka-connectors_image:
          <<: *release_filter
          requires:
            - build_kafka-connectors