global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'markets-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080','localhost:8081','host.docker.internal:8080','host.docker.internal:8081']